name: Deploy

on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencues
        run: echo "No installing required"

      - name: Build Site
        run: echo "Building"

      - name: Deploying site
        uses: peaceiris/actions-gh-pages@v4
        with: 
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./
